dist: xenial

language: node_js
node_js:
  - "10"

install:
  - npm install

script:
  - npm run build

#after_success:

# Monitor only these branches
branches:
  only:
    - master

# $HOME/.npm
cache: npm

# https://docs.travis-ci.com/user/deployment/pages/
#before_deploy:

# https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  target-branch:  'gh-pages'
  local-dir:  'dist/my-first-ng-app'
  on:
    branch:
      - master
